name: Deploy to GCP

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up gcloud SDK
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: components update

      - name: Create push subscription for pubsub topic 'orders'
        # if subscription already exists this call will fail but that is OK
        continue-on-error: true
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: pubsub subscriptions create --topic projects/${{ secrets.GCLOUD_PROJECT_ID }}/topics/orders --expiration-period=1d order-processor

      - name: Deploy function with an HTTP trigger
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: functions deploy order_processor --runtime python37 --trigger-http --memory=128MB
