name: Build Docker Container

on:
  push:
    branches:
      - docker*
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker Container
        run: |
          docker build -t hub.docker.io/kofc7186/print-client:latest .