name: Build Docker Container

on:
  push:
    branches:
      - docker*
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: |
          docker login -u $ {{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker Container
        run: |
          docker build -t kofc7186/print-client:latest .
      - name: Publish Docker Container
        run: |
          docker push -t kofc7186/print-client:latest